-- =============================================================================
-- COD E-Commerce Platform — initial schema, RLS, and RPCs
-- Money is stored as integer DZD (no subunit). RLS is default-deny everywhere.
-- =============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ===========================================================================
-- profiles (admin / commercial users) — mirrors auth.users, RLS anchor
-- ===========================================================================
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text,
  full_name  text,
  role       text not null default 'commercial' check (role in ('admin','commercial')),
  created_at timestamptz not null default now()
);

-- New auth users automatically get a profile row (no public signups; you
-- provision admins via the Supabase dashboard / invite).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- is_admin(): single source of truth for "is the caller a provisioned user".
-- SECURITY DEFINER avoids RLS recursion on profiles.
create or replace function public.is_admin()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid());
$$;

-- ===========================================================================
-- Geography: wilayas, communes, delivery_fees
-- ===========================================================================
create table public.wilayas (
  code       smallint primary key,
  name_fr    text not null,
  name_ar    text not null,
  ascii_name text
);

create table public.communes (
  id          integer primary key generated by default as identity,
  wilaya_code smallint not null references public.wilayas(code),
  name_fr     text not null,
  name_ar     text not null,
  post_code   text
);
create index idx_communes_wilaya on public.communes(wilaya_code);

create table public.delivery_fees (
  wilaya_code        smallint primary key references public.wilayas(code),
  home_fee           integer not null default 0 check (home_fee >= 0),
  stopdesk_fee       integer not null default 0 check (stopdesk_fee >= 0),
  home_available     boolean not null default true,
  stopdesk_available boolean not null default true
);

-- ===========================================================================
-- products
-- ===========================================================================
create table public.products (
  id                uuid primary key default gen_random_uuid(),
  slug              text unique not null,
  name_fr           text not null,
  name_ar           text not null,
  description_fr    text,
  description_ar    text,
  price             integer not null check (price >= 0),       -- DZD
  compare_at_price  integer check (compare_at_price >= 0),     -- optional "old price"
  stock_quantity    integer not null default 0 check (stock_quantity >= 0),
  reserved_quantity integer not null default 0 check (reserved_quantity >= 0),
  is_active         boolean not null default true,
  images            jsonb not null default '[]'::jsonb,        -- storage paths, [0] = cover
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index idx_products_active on public.products(is_active) where is_active = true;
create index idx_products_slug on public.products(slug);

create trigger trg_products_updated
  before update on public.products
  for each row execute function public.set_updated_at();

-- ===========================================================================
-- orders + order_items
-- ===========================================================================
create table public.orders (
  id              uuid primary key default gen_random_uuid(),
  order_number    bigint generated by default as identity,
  customer_name   text not null,
  customer_phone  text not null,
  wilaya_code     smallint not null references public.wilayas(code),
  commune_id      integer not null references public.communes(id),
  address         text,
  delivery_method text not null check (delivery_method in ('home','stopdesk')),
  delivery_fee    integer not null default 0,   -- snapshot
  subtotal        integer not null default 0,   -- snapshot
  total           integer not null default 0,   -- snapshot
  status          text not null default 'pending'
                    check (status in ('pending','confirmed','shipped','delivered','cancelled','returned')),
  notes           text,
  meta_event_id   uuid,                          -- Pixel/CAPI dedup key
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  confirmed_at    timestamptz
);
create index idx_orders_status on public.orders(status);
create index idx_orders_created on public.orders(created_at desc);

create trigger trg_orders_updated
  before update on public.orders
  for each row execute function public.set_updated_at();

create table public.order_items (
  id              uuid primary key default gen_random_uuid(),
  order_id        uuid not null references public.orders(id) on delete cascade,
  product_id      uuid not null references public.products(id) on delete restrict,
  quantity        integer not null check (quantity > 0),
  unit_price      integer not null,             -- snapshot of product.price
  product_name_fr text,
  product_name_ar text
);
create index idx_order_items_order on public.order_items(order_id);
create index idx_order_items_product on public.order_items(product_id);

-- ===========================================================================
-- stock_movements (audit ledger)
-- ===========================================================================
create table public.stock_movements (
  id         uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id),
  order_id   uuid references public.orders(id) on delete set null,
  delta      integer not null,
  type       text not null check (type in ('reserve','release','decrement','restock','manual')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);
create index idx_stock_movements_product on public.stock_movements(product_id);

-- ===========================================================================
-- settings (single row)
-- ===========================================================================
create table public.settings (
  id                      boolean primary key default true check (id),
  store_name              text not null default 'Ma Boutique',
  meta_pixel_id           text,
  free_shipping_threshold integer,
  updated_at              timestamptz not null default now()
);
insert into public.settings (id) values (true) on conflict (id) do nothing;

create trigger trg_settings_updated
  before update on public.settings
  for each row execute function public.set_updated_at();

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
alter table public.profiles        enable row level security;
alter table public.wilayas         enable row level security;
alter table public.communes        enable row level security;
alter table public.delivery_fees   enable row level security;
alter table public.products        enable row level security;
alter table public.orders          enable row level security;
alter table public.order_items     enable row level security;
alter table public.stock_movements enable row level security;
alter table public.settings        enable row level security;

-- profiles: admins manage; users can read their own row
create policy profiles_select_self on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy profiles_admin_all   on public.profiles for all using (public.is_admin()) with check (public.is_admin());

-- products: public reads active; admins read/write everything
create policy products_public_read on public.products for select using (is_active = true);
create policy products_admin_read  on public.products for select using (public.is_admin());
create policy products_admin_write on public.products for all using (public.is_admin()) with check (public.is_admin());

-- geo + fees: public read; admin write
create policy wilayas_public_read on public.wilayas for select using (true);
create policy wilayas_admin_write on public.wilayas for all using (public.is_admin()) with check (public.is_admin());

create policy communes_public_read on public.communes for select using (true);
create policy communes_admin_write on public.communes for all using (public.is_admin()) with check (public.is_admin());

create policy delivery_fees_public_read on public.delivery_fees for select using (true);
create policy delivery_fees_admin_write on public.delivery_fees for all using (public.is_admin()) with check (public.is_admin());

-- orders / order_items: admin-only direct access. Public order creation goes
-- through the create_order() RPC (SECURITY DEFINER), never a direct INSERT.
create policy orders_admin_all      on public.orders      for all using (public.is_admin()) with check (public.is_admin());
create policy order_items_admin_all on public.order_items for all using (public.is_admin()) with check (public.is_admin());

-- stock_movements + settings: admin-only
create policy stock_movements_admin_all on public.stock_movements for all using (public.is_admin()) with check (public.is_admin());
create policy settings_admin_read  on public.settings for select using (public.is_admin());
create policy settings_admin_write on public.settings for all using (public.is_admin()) with check (public.is_admin());

-- =============================================================================
-- RPC: create_order — recomputes totals server-side, reserves stock atomically
-- p_items: jsonb array of { "product_id": uuid, "quantity": int }
-- =============================================================================
create or replace function public.create_order(
  p_customer_name   text,
  p_customer_phone  text,
  p_wilaya_code     smallint,
  p_commune_id      integer,
  p_address         text,
  p_delivery_method text,
  p_items           jsonb
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_fee_row     public.delivery_fees%rowtype;
  v_item        jsonb;
  v_product     public.products%rowtype;
  v_qty         integer;
  v_subtotal    integer := 0;
  v_delivery    integer;
  v_order_id    uuid;
  v_order_num   bigint;
  v_event_id    uuid := gen_random_uuid();
  v_reserved_id uuid;
begin
  if p_delivery_method not in ('home','stopdesk') then
    raise exception 'invalid_delivery_method';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_order';
  end if;

  -- commune must belong to the chosen wilaya
  if not exists (select 1 from public.communes where id = p_commune_id and wilaya_code = p_wilaya_code) then
    raise exception 'invalid_commune_for_wilaya';
  end if;

  -- delivery fee + availability for the chosen method
  select * into v_fee_row from public.delivery_fees where wilaya_code = p_wilaya_code;
  if not found then
    raise exception 'no_delivery_to_wilaya';
  end if;
  if p_delivery_method = 'home' then
    if not v_fee_row.home_available then raise exception 'home_delivery_unavailable'; end if;
    v_delivery := v_fee_row.home_fee;
  else
    if not v_fee_row.stopdesk_available then raise exception 'stopdesk_unavailable'; end if;
    v_delivery := v_fee_row.stopdesk_fee;
  end if;

  -- create the order shell first (so order_items + movements can reference it)
  insert into public.orders (customer_name, customer_phone, wilaya_code, commune_id,
                             address, delivery_method, delivery_fee, subtotal, total,
                             status, meta_event_id)
  values (p_customer_name, p_customer_phone, p_wilaya_code, p_commune_id,
          p_address, p_delivery_method, v_delivery, 0, v_delivery, 'pending', v_event_id)
  returning id, order_number into v_order_id, v_order_num;

  -- process each line: validate, reserve atomically, snapshot price
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := coalesce((v_item->>'quantity')::int, 0);
    if v_qty <= 0 then raise exception 'invalid_quantity'; end if;

    -- atomic conditional reserve: only succeeds if enough is available
    update public.products
       set reserved_quantity = reserved_quantity + v_qty
     where id = (v_item->>'product_id')::uuid
       and is_active = true
       and (stock_quantity - reserved_quantity) >= v_qty
    returning id into v_reserved_id;

    if v_reserved_id is null then
      -- distinguishes "out of stock" from "no such active product"
      if not exists (select 1 from public.products where id = (v_item->>'product_id')::uuid and is_active) then
        raise exception 'product_unavailable';
      end if;
      raise exception 'insufficient_stock';
    end if;

    select * into v_product from public.products where id = v_reserved_id;
    v_subtotal := v_subtotal + (v_product.price * v_qty);

    insert into public.order_items (order_id, product_id, quantity, unit_price,
                                    product_name_fr, product_name_ar)
    values (v_order_id, v_product.id, v_qty, v_product.price,
            v_product.name_fr, v_product.name_ar);

    insert into public.stock_movements (product_id, order_id, delta, type)
    values (v_product.id, v_order_id, v_qty, 'reserve');
  end loop;

  -- finalize totals
  update public.orders
     set subtotal = v_subtotal, total = v_subtotal + v_delivery
   where id = v_order_id;

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_order_num,
    'subtotal', v_subtotal,
    'delivery_fee', v_delivery,
    'total', v_subtotal + v_delivery,
    'meta_event_id', v_event_id
  );
end;
$$;

revoke all on function public.create_order(text,text,smallint,integer,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,smallint,integer,text,text,jsonb) to anon, authenticated;

-- =============================================================================
-- RPC: update_order_status — admin-only state machine with stock side-effects
-- =============================================================================
create or replace function public.update_order_status(
  p_order_id uuid,
  p_status   text
) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_old   text;
  v_admin uuid := auth.uid();
  v_item  record;
begin
  if not public.is_admin() then
    raise exception 'not_authorized';
  end if;

  select status into v_old from public.orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if v_old = p_status then return; end if;

  -- allowed transitions
  if not (
    (v_old = 'pending'   and p_status in ('confirmed','cancelled')) or
    (v_old = 'confirmed' and p_status in ('shipped','cancelled','returned')) or
    (v_old = 'shipped'   and p_status in ('delivered','cancelled','returned')) or
    (v_old = 'delivered' and p_status in ('returned'))
  ) then
    raise exception 'illegal_transition_% _to_%', v_old, p_status;
  end if;

  -- stock side-effects per item. While 'pending', stock is held in
  -- reserved_quantity. On confirm we convert reserve -> physical decrement.
  -- On cancel/return we release the reserve (if still pending) or restock.
  for v_item in select product_id, quantity from public.order_items where order_id = p_order_id
  loop
    if v_old = 'pending' and p_status = 'confirmed' then
      update public.products
         set reserved_quantity = reserved_quantity - v_item.quantity,
             stock_quantity    = stock_quantity - v_item.quantity
       where id = v_item.product_id;
      insert into public.stock_movements (product_id, order_id, delta, type, created_by)
      values (v_item.product_id, p_order_id, -v_item.quantity, 'decrement', v_admin);

    elsif v_old = 'pending' and p_status = 'cancelled' then
      update public.products
         set reserved_quantity = reserved_quantity - v_item.quantity
       where id = v_item.product_id;
      insert into public.stock_movements (product_id, order_id, delta, type, created_by)
      values (v_item.product_id, p_order_id, v_item.quantity, 'release', v_admin);

    elsif p_status in ('cancelled','returned') and v_old in ('confirmed','shipped','delivered') then
      -- physical stock was already decremented at confirm; put it back
      update public.products
         set stock_quantity = stock_quantity + v_item.quantity
       where id = v_item.product_id;
      insert into public.stock_movements (product_id, order_id, delta, type, created_by)
      values (v_item.product_id, p_order_id, v_item.quantity, 'restock', v_admin);
    end if;
  end loop;

  update public.orders
     set status = p_status,
         confirmed_at = case when p_status = 'confirmed' then now() else confirmed_at end
   where id = p_order_id;
end;
$$;

revoke all on function public.update_order_status(uuid,text) from public;
grant execute on function public.update_order_status(uuid,text) to authenticated;
